POS/POS.Web/Controllers/AJAXController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.ViewModel;
using POS.Model;
using POS.DAL;
using Microsoft.AspNet.Identity;

namespace POS.Web.Controllers
{
    public class AJAXController : Controller
    {
        // GET: AJAX
        public ActionResult GetItem()
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletid(OutletId);
            return PartialView("_ListItem",model);
        }

        public ActionResult GetItemSearch(string searchKey)
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletSearch(searchKey, OutletId);
            return PartialView("_ListItem",model);
        }

        public ActionResult GetOutlet()
        {
            List<Outlet> model = OutletDAL.GetData();
            return PartialView("_ListOutlet", model);
        }

        public ActionResult GetOutletSearch(string searchKey)
        {
            List<Outlet> model = OutletDAL.GetDataBySearchKey(searchKey);
            return PartialView("_ListOutlet", model);
        }

        public ActionResult LoadTable()
        {
            List<EmployeViewModel> model = EmployeeDAL.GetDataTable();
            return PartialView("_LoadTable", model);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetItems()
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemsViewModel> model = ItemsDAL.GetData(OutletId);
            return PartialView("_ListItems", model);
        }

        public ActionResult GetItemsSearch(string searchKey)
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemsViewModel> models = ItemsDAL.GetDataSearch(searchKey, OutletId);
            return PartialView("_ListItems", models);
        }


        public ActionResult GetCustomers()
        {
            List<CustomersViewModel> model = CustomersDAL.GetData();
            return PartialView("_ListCustomers", model);
        }

        public ActionResult GetCustomersSearch(string searchKey)
        {
            List<CustomersViewModel> models = CustomersDAL.GetDataSearch(searchKey);
            return PartialView("_ListCustomers", models);
        }


        public JsonResult GetRegion(int provinceId)
        {
            return Json(RegionDAL.GetDataByProvinceId(provinceId),
                JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDistrict(int regionId)
        {
            return Json(DistrictDAL.GetDataByRegionId(regionId),
                JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetVariant()
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletid(OutletId);
            return PartialView("_Variant", model);
        }
        public ActionResult GetVariantSearchTransfer(string SearchKey)
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletSearch(SearchKey, OutletId);
            return PartialView("_Variant", model);
        }
        public ActionResult GetItemVariant()
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletid(OutletId);
            return PartialView("_Add", model);
        }
        public ActionResult GetVariantSearchAdj(string SearchKey)
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletSearch(SearchKey, OutletId);
            return PartialView("_Add", model);
        }

        public ActionResult SearchCategories(string searchkey)
        {
            List<CategoriesViewModel> result = CategoriesDAL.GetSearchCategories(searchkey);
            return PartialView("_ListCategories", result);
        }

        public ActionResult SearchSuppliers(string searchkey)
        {
            List<SuppliersViewModel> result = SuppliersDAL.GetSearch(searchkey);
            return PartialView("_ListSuppliers", result);
        }

        public ActionResult SearchItemsinCategories(string searchkey)
        {
            List<ItemsViewModel> result = CategoriesDAL.GetSearchListItem(searchkey);
            return PartialView("_ListItems1", result);
        }
    }
}

POS/POS.Web/Controllers/PurchaseOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.DAL;
using POS.Model;
using POS.ViewModel;
using Microsoft.AspNet.Identity;

namespace POS.Web.Controllers
{
    [Authorize]
    public class PurchaseOrderController : Controller
    {
        // GET: PurchaseOrder
        public ActionResult Index()
        {
            List<PurchaseOrderViewModel> model = PurchaseOrderDAL.GetData();
            ViewBag.ListStatus = new SelectList(PurchaseOrderDAL.GetStatus(),"ID","StatusName");
            return View(model);
        }

        public ActionResult Load()
        {
            List<PurchaseOrderViewModel> model = PurchaseOrderDAL.GetData();
            return PartialView("_Index",model);
        }

        public ActionResult GetDataByStatus(int id) 
        {
            List<PurchaseOrderViewModel> model = PurchaseOrderDAL.GetDataByStatus(id);
            return PartialView("_Index", model);
        
        }

        public ActionResult GetDataSearch(string searchKey)
        {
            List<PurchaseOrderViewModel> model = PurchaseOrderDAL.GetDataBySearch(searchKey);
            return PartialView("_Index", model);
        }

        public ActionResult Add()
        {
            var UserId = User.Identity.GetUserId();
            ViewBag.ListOutlet = new SelectList(EmployeeOutletDAL.GetDataByID(int.Parse(UserId)), "OutletID", "OutletName");
            ViewBag.ListSupplier = new SelectList(SuppliersDAL.GetData(), "ID", "Name");
            return PartialView("Add");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Add(PurchaseOrderViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (POSContext context = new POSContext())
                {
                    using (var dbTransaction = context.Database.BeginTransaction())
                    {
                        int UserId = User.Identity.GetUserId<int>();
                        string OrderNo = PurchaseOrderDAL.OrderNo();
                        PurchaseOrder order = new PurchaseOrder()
                        {
                            OutletID = model.OutletID,
                            OrderNo = OrderNo,
                            StatusID = 1,
                            SupplierID = model.SupplierID,
                            Notes = model.Notes,
                            Total = model.Total,
                            CreatedBy = UserId,
                            CreatedOn = DateTime.Now,
                            ModifiedBy = UserId,
                            ModifiedOn = DateTime.Now
                        };
                        context.TPurchaseOrder.Add(order);
                        context.SaveChanges();


                        PurchaseOrderHistory orderhis = new PurchaseOrderHistory()
                        {

                            HeaderID = order.ID,
                            StatusID = 1,
                            CreatedBy = UserId,
                            CreatedOn = DateTime.Now,
                            ModifiedBy = UserId,
                            ModifiedOn = DateTime.Now
                        };
                        context.TPurchaseOrderHistory.Add(orderhis);
                        context.SaveChanges();
                        foreach (var item in model.VariantID)
                        {
                            PurchaseOrderDetail orderdetail = new PurchaseOrderDetail()
                            {

                                HeaderID = order.ID,
                                Quantity = model.Quantity,
                                SubTotal = model.SubTotal,
                                VariantID = item,
                                UnitCost = model.UnitCost,
                                CreatedBy = UserId,
                                CreatedOn = DateTime.Now,
                                ModifiedBy = UserId,
                                ModifiedOn = DateTime.Now
                            };
                            context.TPurchaseOrderDetail.Add(orderdetail);
                        }
                        context.SaveChanges();


                        try
                        {
                            dbTransaction.Commit();
                            return RedirectToAction("Index");
                        }
                        catch (Exception)
                        {

                            dbTransaction.Rollback();
                        }
                    }
                }
            }
            return PartialView("Add", model);
        }

        public ActionResult OrderDetail()
        {
            return PartialView("OrderDetail");
        }

        public ActionResult Detail(int Id)
        {
            ListPurchaseOrderViewModel model = PurchaseOrderDAL.GetDataByIdPO(Id);
            return PartialView("Detail", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Detail(ListPurchaseOrderViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (POSContext context = new POSContext())
                {
                    using (var dbTransacyion = context.Database.BeginTransaction())
                    {
                        int UserId = User.Identity.GetUserId<int>();
                        PurchaseOrder item = context.TPurchaseOrder.Where(m => m.ID == model.ID).FirstOrDefault();
                        item.StatusID = model.StatusID;
                        item.ModifiedBy = UserId;
                        item.ModifiedOn = DateTime.Now;
                        context.SaveChanges();

                        PurchaseOrderHistory item2 = new PurchaseOrderHistory()
                        {
                            HeaderID = item.ID,
                            StatusID = model.StatusID,
                            CreatedBy = UserId,
                            ModifiedBy = UserId,
                            CreatedOn = DateTime.Now,
                            ModifiedOn = DateTime.Now
                        };
                        context.TPurchaseOrderHistory.Add(item2);
                        context.SaveChanges();

                        if (model.StatusID == 2)
                        {
                            int i = 0;
                            foreach (var data in model.VariantID)
                            {
                                int variantid = data;
                                ItemsIventory item3 = context.TItemsIventory.Where(m => m.VariantID == variantid).FirstOrDefault();
                                item3.PurchaseOrder = model.Quantity[i];
                                i++;
                            }
                            context.SaveChanges();
                        }

                        try
                        {
                            dbTransacyion.Commit();
                            return RedirectToAction("Index");
                        }
                        catch (Exception)
                        {

                            throw;
                        }
                    }
                }
            }
            return PartialView("Detail", model);
        }


        public ActionResult Edit(int Id)
        {
            var UserId = User.Identity.GetUserId();

            ViewBag.ListOutlet = new SelectList(EmployeeOutletDAL.GetDataByID(int.Parse(UserId)), "OutletID", "OutletName");
            ViewBag.ListSupplier = new SelectList(SuppliersDAL.GetData(), "ID", "Name");
            ListPurchaseOrderViewModel model = PurchaseOrderDAL.GetDataByIdPO(Id);
            return PartialView("Edit", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit(ListPurchaseOrderViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (POSContext context = new POSContext())
                {
                    using (var dbTransaction = context.Database.BeginTransaction())
                    {
                        int UserId = User.Identity.GetUserId<int>();
                        string OrderNo = PurchaseOrderDAL.OrderNo();
                        PurchaseOrder order = context.TPurchaseOrder.Where(m => m.ID == model.ID).FirstOrDefault();
                        if (order != null)
                        {
                            order.OutletID = model.OutletID;
                            order.SupplierID = model.SupplierID;
                            order.Notes = model.Notes;
                            order.Total = model.Total;
                            order.ModifiedBy = UserId;
                            order.ModifiedOn = DateTime.Now;
                        }

                        context.SaveChanges();

                        int i = 0;
                        foreach (var item in model.VariantID)
                        {
                            int POid = model.PODetailID[i];
                            PurchaseOrderDetail orderdetail = context.TPurchaseOrderDetail.Where(m => m.ID == POid).FirstOrDefault();
                            if (orderdetail != null)
                            {
                                orderdetail.HeaderID = order.ID;
                                orderdetail.Quantity = model.Quantity[i];
                                orderdetail.SubTotal = model.SubTotal[i];
                                orderdetail.VariantID = item;
                                orderdetail.UnitCost = model.UnitCost[i];
                                orderdetail.ModifiedBy = UserId;
                                orderdetail.ModifiedOn = DateTime.Now;
                            }
                            else
                            {

POS/POS.Web/Views/PurchaseOrder/Index.cshtml
@model IEnumerable<POS.ViewModel.PurchaseOrderViewModel>


<h2>Pruschase Order</h2>

<b></b>
<div class=" box">
    <div class="box-header">
        <div class="input-group">
            <input type="text" id="search-txt" class="form-control" placeholder="Search Key" />
            <span class="input-group-btn">
                <button class="btn btn-primary" id="btn-srcindex"><i class="fa fa-search"></i></button>
            </span>

            <div class="col-md-3">
                @Html.DropDownList("StatusID", (IEnumerable<SelectListItem>)ViewBag.ListStatus, "All Status", new { @class = "form-control" })
            </div>
            <div class="col-md-2">
                <button id="export-po" type="button" class="btn btn-primary btn-sm">Export</button>
            </div>
            <div class="col-md-2">
                <button type="button" class="btn btn-primary btn-sm create-po">Create Purchase Order</button>
            </div>
        </div>

    </div>
    <div id="content" class="box-body">

    </div>
</div>

@*menampilkan menu detail*@
<div id="modal-podetailedit" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div id="modal-podetailedit-data" class="modal-body">

            </div>

        </div>
    </div>
</div>

@*menampilkan Pop Up pada halaman pertama untuk manampilkan create purchase order*@
<div id="modal-purchaseorder" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div id="modal-purchaseorder-data" class="modal-body">

            </div>

        </div>
    </div>
</div>

@*menampilkan Pop Up yang kedua pada saat klik tombol add po pada pop up create po  maka muncul nama item yang mau ditambahkan*@
<div id="modal-podetail" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div id="modal-podetail-data" class="modal-body">

            </div>

        </div>
    </div>
</div>



@*menampilkan Pop Up yang ketiga klik tombol search di modal untuk mencari item yang mau ditambahkan serta untuk search item*@
<div id="search-item-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

            </div>

            <div class="modal-body">
                <div class="input-group">
                    <input type="text" id="search-txt2" class="form-control" placeholder="Mencari Item" />
                    <span class="input-group-btn">
                        <button class="btn btn-primary" id="btn-srcitem"><i class="fa fa-search"></i></button>
                    </span>
                </div>
                <div class="row">
                    <div id="search-data-itemvariant" class="col-md-12">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script type="text/javascript">
        function LoadData() {
            $.ajax({
                url: '@Url.Action("Load","PurchaseOrder")',
                dataType: 'html',
                type: 'GET',
                success: function (result) {
                    $('#content').html(result);
                }
            });
        };
        $(document).ready(function () {
            LoadData();
            $('#order').val('0');
            $('#unit-cost').val('0');

            $("#StatusID").change(function () {
                var vId = $(this).val();
                if (vId == 0) {
                    LoadData();
                }
                else {
                    $.ajax({
                        url: "@Url.Action("GetDataByStatus", "PurchaseOrder")",
                        data: { id: vId },
                        dataType: 'html',
                        type: 'GET',
                        success: function (result) {
                            $("#content").html(result);
                        },
                    });
                }

            });

        //meanampilkan edit
            $('#modal-podetailedit-data').on('click', '.click-edit', function () {
                var vID = $(this).attr('data-id');
                $.ajax({
                    url: '@Url.Action("Edit","PurchaseOrder")',
                    data: { Id: vID },
                    dataType: 'html',
                    type: 'GET',
                    success: function (result) {
                        $('#modal-purchaseorder-data').html(result);
                        $('#modal-purchaseorder').modal('show');
                    }
                });
            });

            //menampilkan detail
            $('#content').on('click', '.btn-detail', function () {
                var vStatus = $(this).attr('data-status');
                var vId = $(this).attr('data-id');
                if (vStatus > 1) {
                    $(this).empty;
                }
                else {
                    $.ajax({
                        url: '@Url.Action("Detail", "PurchaseOrder")',
                        data: { Id: vId },
                        dataType: 'html',
                        type: 'GET',
                        success: function (result) {
                            $('#modal-podetailedit-data').html(result);
                            $('#modal-podetailedit').modal('show');
                        }
                    });
                }

            });
            //pop up add purchase order(tombol create po)
            $('.create-po').click(function () {
                $.ajax({
                    url: '@Url.Action("Add","PurchaseOrder")',
                    dataType: 'html',
                    type: 'GET',
                    success: function (result) {
                        $('#modal-purchaseorder-data').html(result);
                        $('#modal-purchaseorder').modal('show');
                    }
                });
            });
            //Pop up order details(tombol add po)
            $('#modal-purchaseorder-data').on('click', '.btn-add-po', function (e) {
                e.preventDefault();
                $.ajax({
                    url: '@Url.Action("OrderDetail", "PurchaseOrder")',
                    dataType: 'html',
                    type: 'GET',
                    success: function (result) {
                        $('#modal-podetail-data').html(result);
                        $('#modal-podetail').modal('show');
                    }
                });
            });
            //popup menampilkan item
            $('#modal-podetail-data').on('click', '#btn-src-item', function (e) {
                e.preventDefault();
                $.ajax({
                    url: '@Url.Action("GetItem", "AJAX")',
                    dataType: 'html',
                    type: 'GET',
                    success: function (result) {
                        $("#search-data-itemvariant").html(result);
                        $("#search-item-modal").modal('show');
                    },
                });
            });

            //tombol search index
            $('#btn-srcindex').click(function () {
                var txtSearch = $("#search-txt").val();
                    $.ajax({
                        url: '@Url.Action("GetDataSearch", "PurchaseOrder")',
                        data: { searchKey: txtSearch },
                        dataType: 'html',
                        type: 'GET',
                        success: function (result) {
                            $("#content").html(result);
                        },
                    });
            });

            //tombol search item
            $('#btn-srcitem').click(function () {
                var txtSearch = $("#search-txt2").val();
                $.ajax({
                    url: '@Url.Action("GetItemSearch", "AJAX")',
                    data: { searchKey: txtSearch },
                    dataType: 'html',
                    type: 'GET',
                    success: function (result) {
                        $("#search-data-itemvariant").html(result);
                    },
                });
            });

           


            //menambahkan data pada saat kilk tombol ceklis
            $("#search-data-itemvariant").on("click", ".btn-ok-item", function (e) {
                e.preventDefault();
                var vID = $(this).attr("data-id");
                var vNamaVariant = $(this).attr("data-NamaVariant");
                var vstok = $(this).attr("data-stok");
                var vData =
                    '<tr>' +
                        '<td><input type="hidden" name="VariantID" value="' + vID + '"/>' + ' <input type="hidden" name="PODetailID" value="' + 0 + '"/>' + vNamaVariant +
                        '</td>' +
                        '<td>' + vstok + '</td>' +
                        '<td><input name="Quantity" type="text" class="orderc form-control read" style="width:60px;" id="order_' + vID + '"/></td>' +
                        '<td><input name="UnitCost" type="text" class="unit-cost form-control read" style="width:100px;" id ="unitcost_' + vID + '"/></td>' +
                        '<td><input name="SubTotal" type="text" class="totalc form-control read" style="width:100px;" id="total_' + vID + '" readonly="readonly"/></td>' +
                        '<td><button type="button" class="btn btn-danger btn-xs btn-del-item"><i class="fa fa-trash-o" ></i></button></td>' +
                    '</tr>';

                $("#list-detail-item").append(vData);
                $("#search-item-modal").modal('hide');
            });
            //hitung subtotal
            $('#modal-podetail-data').on('change', '.unit-cost,.orderc', function (e) {
                e.preventDefault();
                var order = $(this).parent().parent().find(".orderc").val();
                var unitcost = $(this).parent().parent().find('.unit-cost').val();
                var subtotal = parseInt(order) * parseInt(unitcost);
                $(this).parent().parent().find('.totalc').val(subtotal);
            });


            //mendelete data yang sudah ditambahkan di modal po detail
            $("#modal-podetail-data").on("click", ".btn-del-item", function (e) {
                e.preventDefault();
                $(this).parent().parent().remove();
            });

            //mendelete data yang sudah ditambahkan di modal po create
            $("#modal-purchaseorder-data").on("click", ".btn-del-item", function (e) {
                e.preventDefault();
                $(this).parent().parent().remove();
            });
            //add data ke modal po
            $('#modal-podetail-data').on('click', '.btn-save', function (e) {
                e.preventDefault();

                var aData = $('#list-detail-item').contents();
                $('#list-detail-po').append(aData);
                $(":disabled");
            });

            //save data purchase order
            $("#modal-purchaseorder-data").on("submit", "form-addpurchaseorder", function (e) {
                e.preventDefault();
                var vData = $(this).serialize();
                var vUrl = $(this).attr('action');
                var vMethod = $(this).attr('method');
                $.ajax({
                    url: vUrl,
                    data: vData,
                    method: vMethod,
                    success: function (result) {
                        if (result.success) {
                            $('#modal-purchaseorder').modal('hide')
                        }
                        else {
                            $('#modal-purchaseorder-data').html('show')
                        }
                    }
                });
            });

        });
    </script>
}

POS/POS.Web/Views/PurchaseOrder/OrderDetail.cshtml
@model POS.ViewModel.PurchaseOrderDetailsViewModel

<h4 class="text-center">Add Purchase Order</h4>
<hr />

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Item", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                <div class="input-group">
                    @Html.HiddenFor(model => model.VariantID, new { @class = "form-control" })
                    <input type="text" id="NamaItem" class="form-control" />
                    <div class="input-group-btn">
                        <button type="button" id="btn-src-item" class="btn btn-flat btn-primary">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>

                @Html.ValidationMessageFor(model => model.VariantID, "", new { @class = "text-danger" })
            </div>
        </div>
        
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>In Stok</th>
                        <th>Order</th>
                        <th>Unit Cost</th>
                        <th>Total</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="list-detail-item"></tbody>
            </table>
    
    <div class="modal-footer">
        <div class="col-md-2 pull-right">
            <button type="button" class="btn btn-primary  btn-save col-md-12" data-dismiss="modal">Add</button>
        </div>
        <div class="col-md-2 pull-left">
            <button type="button" class="btn btn-default col-md-12" data-dismiss="modal">Cancel</button>
        </div>
    </div>
    </div>
}