POS/POS.Web/Controllers/AJAXController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.ViewModel;
using POS.Model;
using POS.DAL;
using Microsoft.AspNet.Identity;

namespace POS.Web.Controllers
{
    public class AJAXController : Controller
    {
        // GET: AJAX
        public ActionResult GetItem()
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletid(OutletId);
            return PartialView("_ListItem",model);
        }

        public ActionResult GetItemSearch(string searchKey)
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletSearch(searchKey, OutletId);
            return PartialView("_ListItem",model);
        }

        public ActionResult GetOutlet()
        {
            List<Outlet> model = OutletDAL.GetData();
            return PartialView("_ListOutlet", model);
        }

        public ActionResult GetOutletSearch(string searchKey)
        {
            List<Outlet> model = OutletDAL.GetDataBySearchKey(searchKey);
            return PartialView("_ListOutlet", model);
        }

        public ActionResult LoadTable()
        {
            List<EmployeViewModel> model = EmployeeDAL.GetDataTable();
            return PartialView("_LoadTable", model);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetItems()
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemsViewModel> model = ItemsDAL.GetData(OutletId);
            return PartialView("_ListItems", model);
        }

        public ActionResult GetItemsSearch(string searchKey)
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemsViewModel> models = ItemsDAL.GetDataSearch(searchKey, OutletId);
            return PartialView("_ListItems", models);
        }


        public ActionResult GetCustomers()
        {
            List<CustomersViewModel> model = CustomersDAL.GetData();
            return PartialView("_ListCustomers", model);
        }

        public ActionResult GetCustomersSearch(string searchKey)
        {
            List<CustomersViewModel> models = CustomersDAL.GetDataSearch(searchKey);
            return PartialView("_ListCustomers", models);
        }


        public JsonResult GetRegion(int provinceId)
        {
            return Json(RegionDAL.GetDataByProvinceId(provinceId),
                JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDistrict(int regionId)
        {
            return Json(DistrictDAL.GetDataByRegionId(regionId),
                JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetVariant()
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletid(OutletId);
            return PartialView("_Variant", model);
        }
        public ActionResult GetVariantSearchTransfer(string SearchKey)
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletSearch(SearchKey, OutletId);
            return PartialView("_Variant", model);
        }
        public ActionResult GetItemVariant()
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletid(OutletId);
            return PartialView("_Add", model);
        }
        public ActionResult GetVariantSearchAdj(string SearchKey)
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletSearch(SearchKey, OutletId);
            return PartialView("_Add", model);
        }

        public ActionResult SearchCategories(string searchkey)
        {
            List<CategoriesViewModel> result = CategoriesDAL.GetSearchCategories(searchkey);
            return PartialView("_ListCategories", result);
        }

        public ActionResult SearchSuppliers(string searchkey)
        {
            List<SuppliersViewModel> result = SuppliersDAL.GetSearch(searchkey);
            return PartialView("_ListSuppliers", result);
        }

        public ActionResult SearchItemsinCategories(string searchkey)
        {
            List<ItemsViewModel> result = CategoriesDAL.GetSearchListItem(searchkey);
            return PartialView("_ListItems1", result);
        }
    }
}

POS/POS.Web/Controllers/TransferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.ViewModel;
using POS.DAL;
using POS.Model;
using Microsoft.AspNet.Identity;

namespace POS.Web.Controllers
{
    [Authorize]
    public class TransferController : Controller
    {
        // GET: TransferStock
        public ActionResult Index()
        {
            ViewBag.ListOutlet = new SelectList(OutletDAL.GetData(), "ID", "OutletName");
            var UserId = User.Identity.GetUserId();

            ViewBag.Transfer = new SelectList(EmployeeOutletDAL.GetDataByID(int.Parse(UserId)), "OutletID", "OutletName");
            return View();
        }

        //untuk input data ke dua tabelnabelnya
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(TransferViewModel model) //tambahin kodingan utk rollback
        {
            if (ModelState.IsValid)
            {
                using (POSContext context = new POSContext())
                {
                    using (var dbTransaction = context.Database.BeginTransaction())
                    {

                        int UserId = User.Identity.GetUserId<int>();
                        int OutletId = 0;
                        OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
                        TransferStock item = new TransferStock()
                        {
                            ID = model.ID,
                            FromOutlet = OutletId,
                            ToOutlet = model.ToOutlet,
                            Note = model.Note,
                            CreatedBy = UserId,
                            CreatedOn = DateTime.Now,
                            ModifiedBy = UserId,
                            ModifiedOn = DateTime.Now,
                        };
                        context.TTransferStock.Add(item);
                        try { context.SaveChanges(); }
                        catch (Exception) { }

                        int i = 0;
                        foreach (var detail in model.VariantID) //pakai Sku hasil null, pakai Variant ID hasil null
                        {
                            TransferStockDetail vDetail = new TransferStockDetail()
                            {
                                HeaderID = item.ID,
                                VariantID = detail,
                                InStock = model.InStock[i],
                                Quantity = model.Quantity[i],

                                CreatedBy = UserId,
                                CreatedOn = DateTime.Now,
                                ModifiedBy = UserId,
                                ModifiedOn = DateTime.Now,
                            };
                            context.TTransferStockDetail.Add(vDetail);

                            ItemsIventory vInv = context.TItemsIventory.Where(t => t.VariantID == detail).FirstOrDefault();
                            if (vInv != null)
                            {
                                vInv.VariantID = detail;
                                vInv.Beginning = model.InStock[i];
                                vInv.Transfer = model.Quantity[i];
                                vInv.CreatedBy = UserId;
                                vInv.CreatedOn = DateTime.Now;
                                vInv.ModifiedBy = UserId;
                                vInv.ModifiedOn = DateTime.Now;
                            };
                            try { context.SaveChanges(); }
                            catch (Exception) { }
                            i++;
                        }


                        try
                        {
                            dbTransaction.Commit();
                            return RedirectToAction("Index");
                        }
                        catch (Exception)
                        {

                            dbTransaction.Rollback();
                        }
                    }
                }
            }
            return View("Index", model);
        }
    }
}

POS/POS.Web/Views/Transfer/Index.cshtml
@model POS.ViewModel.TransferViewModel

<div class="box box-info">
    <div class="box-header">
        <div class="box-header">
            <h4 class="box-title">Choose Outlet</h4>
        </div>
    </div>
    <div class="box-body">

        @using (Html.BeginForm("Index", "Transfer", null, FormMethod.Post, new { @id = "form-transfer" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.FromOutlet, new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.DropDownListFor(model => model.FromOutlet, (IEnumerable<SelectListItem>)ViewBag.Transfer, new { @class = "form-control", @disabled = "" })
                        @*@Html.TextBoxFor(model => model.FromOutlet, new { @class = "form-control", @readonly = "readonly" })*@
                        @Html.ValidationMessageFor(model => model.FromOutlet, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ToOutlet, new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.DropDownListFor(model => model.ToOutlet, (IEnumerable<SelectListItem>)ViewBag.ListOutlet, "-Pilih Outlet-", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ToOutlet, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Note, new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.TextAreaFor(model => model.Note, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="box" style="margin-left:-10px; margin-right:-20px;">
                <div class="box-header">
                    <h4 class="box-title">Transfer Stock</h4>
                    <div class="box-tools">
                        <div class="input-group input-group-sm" style="width:150px">
                            <div class="input-group-btn">
                                <button id="btn-add-transfer" class="btn btn-primary" type="button">
                                    Add Stock To Transfer
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table table-striped table-bordered ">
                        <thead>
                            <tr>

                                <th class="text-center">Variant Name</th>
                                <th class="text-center">InStock</th>
                                <th class="text-center">Transfer Quantity</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody id="list-detail-transfer"></tbody>
                    </table>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-10 col-md-2">
                    <button class="btn btn-primary" type="submit">
                        Save
                    </button>
                </div>
            </div>
        }
    </div>
</div>

<!-- bagian modal -->

<div id="search-modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 id="search-model-tittle" class="modal-title text-center"></h4>
            </div>
            <div class="modal-body">
                <div class="input-group">
                    <div id="alert-message" style="display:none;" class="alert alert-warning alert-dismissible">
                        <h5><i class="icon fa fa-warning"></i> Warning!</h5>
                        <p id="text-message"></p>
                    </div>
                    <input type="hidden" id="search-type" value="variant" />
                    <input type="text" id="search-txt" class="form-control" placeholder="Search Key" />
                    <span class="input-group-btn">
                        <button class="btn btn-primary" id="btn-src-modal"><i class="fa fa-search"></i></button>
                    </span>
                </div>
                <div class="row">
                    <div id="search-data" class="col-md-12">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(document).ready(function () {

            //script tombol add transfer stock
            $("#btn-add-transfer").click(function () {
                $("#search-model-tittle").html("Add Stock to Transfer")
                $("#search-type").val("variant")
                //alert("tes val")
                $.ajax({
                    url: '@Url.Action("GetVariant", "AJAX")',
                    dataType: 'html',
                    type: 'GET',
                    success: function (result) {
                        $("#search-data").html(result);
                        $("#search-modal").modal('show');
                    },
                });
            });

            //untuk tombol search Item
            $('#btn-src-modal').click(function () {
                var type = $("#search-type").val(); //val gak perlu diisi karen sudah ada val di id btn-src-modal
                var txtSearch = $("#search-txt").val(); //val di search-text adalah yang kita cari di searchkey

                $.ajax({
                    url: '@Url.Action("GetVariantSearchTransfer", "AJAX")',
                    data: { searchKey: txtSearch },
                    dataType: 'html',
                    type: 'GET',
                    success: function (result) {
                        $("#search-data").html(result);
                        //$("#search-modal").modal('show');
                    },
                });
            });
            // untuk mengklik item terpilih
            $("#search-data").on("click", ".btn-ok-transfer", function (e) { //klik ok bapda bagian yang di pilih
                e.preventDefault();

                var vID = $(this).attr("data-id")
                var vName = $(this).attr("data-nama")
                var vInstock = $(this).attr("data-instock")
                var vTransfer = $(this).parent().parent().find(".item-transfer").val();
                var vData = '<tr>' +
                '<td class="text-center"><input type="hidden" name="VariantID" value="' + vID + '"/>' + vName + '</td>' +

                '<td class="text-center"><input type="text" readonly="readonly" name="InStock" value="' + vInstock + '" class="form-control"/></td>' +
                '<td class="text-center"><input type="text" id="jumlah-transfer" name="Quantity" value="' + vTransfer + '" class="form-control"/></td>' +
                '<td class="text-center"><button type="button" class="btn btn-danger btn-xs btn-del-items"><i class="fa fa-trash-o" ></i></button></td>' +
            '</tr>';
                $("#list-detail-transfer").append(vData);
                $("#search-modal").modal('show');
            });
            //untuk menghapus satu baris dari list bila salah
            $("#list-detail-transfer").on("click", ".btn-del-items", function (e) {
                e.preventDefault();
                $(this).parent().parent().remove();
            });
        });
    </script>
}