POS/POS.Web/Controllers/AJAXController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.ViewModel;
using POS.Model;
using POS.DAL;
using Microsoft.AspNet.Identity;

namespace POS.Web.Controllers
{
    public class AJAXController : Controller
    {
        // GET: AJAX
        public ActionResult GetItem()
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletid(OutletId);
            return PartialView("_ListItem",model);
        }

        public ActionResult GetItemSearch(string searchKey)
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletSearch(searchKey, OutletId);
            return PartialView("_ListItem",model);
        }

        public ActionResult GetOutlet()
        {
            List<Outlet> model = OutletDAL.GetData();
            return PartialView("_ListOutlet", model);
        }

        public ActionResult GetOutletSearch(string searchKey)
        {
            List<Outlet> model = OutletDAL.GetDataBySearchKey(searchKey);
            return PartialView("_ListOutlet", model);
        }

        public ActionResult LoadTable()
        {
            List<EmployeViewModel> model = EmployeeDAL.GetDataTable();
            return PartialView("_LoadTable", model);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetItems()
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemsViewModel> model = ItemsDAL.GetData(OutletId);
            return PartialView("_ListItems", model);
        }

        public ActionResult GetItemsSearch(string searchKey)
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemsViewModel> models = ItemsDAL.GetDataSearch(searchKey, OutletId);
            return PartialView("_ListItems", models);
        }


        public ActionResult GetCustomers()
        {
            List<CustomersViewModel> model = CustomersDAL.GetData();
            return PartialView("_ListCustomers", model);
        }

        public ActionResult GetCustomersSearch(string searchKey)
        {
            List<CustomersViewModel> models = CustomersDAL.GetDataSearch(searchKey);
            return PartialView("_ListCustomers", models);
        }


        public JsonResult GetRegion(int provinceId)
        {
            return Json(RegionDAL.GetDataByProvinceId(provinceId),
                JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDistrict(int regionId)
        {
            return Json(DistrictDAL.GetDataByRegionId(regionId),
                JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetVariant()
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletid(OutletId);
            return PartialView("_Variant", model);
        }
        public ActionResult GetVariantSearchTransfer(string SearchKey)
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletSearch(SearchKey, OutletId);
            return PartialView("_Variant", model);
        }
        public ActionResult GetItemVariant()
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletid(OutletId);
            return PartialView("_Add", model);
        }
        public ActionResult GetVariantSearchAdj(string SearchKey)
        {
            int UserId = User.Identity.GetUserId<int>();
            int OutletId = 0;
            OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataByOutletSearch(SearchKey, OutletId);
            return PartialView("_Add", model);
        }

        public ActionResult SearchCategories(string searchkey)
        {
            List<CategoriesViewModel> result = CategoriesDAL.GetSearchCategories(searchkey);
            return PartialView("_ListCategories", result);
        }

        public ActionResult SearchSuppliers(string searchkey)
        {
            List<SuppliersViewModel> result = SuppliersDAL.GetSearch(searchkey);
            return PartialView("_ListSuppliers", result);
        }

        public ActionResult SearchItemsinCategories(string searchkey)
        {
            List<ItemsViewModel> result = CategoriesDAL.GetSearchListItem(searchkey);
            return PartialView("_ListItems1", result);
        }
    }
}

POS/POS.Web/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.DAL;
using POS.Model;
using POS.ViewModel;

namespace POS.Web.Controllers
{
    public class CustomersController : Controller
    {
         //GET: NewCustomer
        public ActionResult Add()
        {
            ViewBag.listProvince = new SelectList(ProvinceDAL.GetData(), "ID", "ProvinceName");
            ViewBag.listRegion = new SelectList(String.Empty,"","");
            ViewBag.listDistrict = new SelectList(String.Empty, "", "");
            CustomersViewModel model = new CustomersViewModel();
            return PartialView("Add", model);
        }

         [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Add(CustomersViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (POSContext context = new POSContext())
                {
                    Customers item = new Customers()
                    {
                        ID = model.ID,
                        CustomerName = model.CustomerName,
                        Email = model.Email,
                        Phone = model.Phone,
                        Address = model.Address,
                        BirthDate = model.BirthDate,
                        CreatedBy = 1,
                        CreatedOn = DateTime.Now,
                        ModifiedBy = 1,
                        ModifiedOn = DateTime.Now,
                        ProvinceID = model.ProvinceID,
                        RegionID = model.RegionID,
                        DistrictID = model.DistrictID,

                    };
                    context.TCustomers.Add(item);
                    try
                    {
                        context.SaveChanges();
                        return RedirectToAction("Add", "Payment");
                    }
                    catch (Exception)
                    {

                        throw;
                    }
                }
            }

            return PartialView("Add", model);
        }
    }
}

POS/POS.Web/Views/Customers/Add.cshtml
@model POS.ViewModel.CustomersViewModel

@using (Html.BeginForm("Add", "Customers", null, FormMethod.Post, new { @id = "form-customers" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            <div class="col-md-12">
                <h5>PROFIL</h5>
            </div>
            <div class="col-md-12">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Name" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-12">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email (Required)" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-12">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", @placeholder = "Phone" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <h5>BIRTHDAY</h5>
            </div>
            <div class="col-md-12">
                @Html.EditorFor(model => model.BirthDate, "{0:dd/MM/yyyy}" , new { htmlAttributes = new { @class = "form-control datepicker", @placeholder = "BirthDate" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <h5>ADDRESS(OPTIONAL)</h5>
            </div>
            <div class="col-md-12">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @placeholder = "Address" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">
                @Html.DropDownListFor(model => model.ProvinceID, (IEnumerable<SelectListItem>)ViewBag.listProvince, "= Chose Provinci =", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProvinceID, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">
                @Html.DropDownListFor(model => model.RegionID, (IEnumerable<SelectListItem>)ViewBag.listRegion, "= Chose Region =", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RegionID, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">
                @Html.DropDownListFor(model => model.DistrictID, (IEnumerable<SelectListItem>)ViewBag.listDistrict, "= Chose District =", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DistrictID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" id="btn-cus-save" class="btn btn-primary btn-block">Simpan</button>
        </div>
    </div>
}
<script type="text/javascript">
    $(document).ready(function () {
        $(".datepicker").datepicker({
            autoclose: true,
            format: 'dd/mm/yyyy',
        });

        $("#ProvinceID").change(function () {
            var vId = $(this).val();
            $.ajax({
                url: "@Url.Action("GetRegion", "AJAX")",
                data: { provinceId: vId },
                dataType: 'json',
                type: 'GET',
                success: function (result) {
                    $("#DistrictID").empty();
                    $("#DistrictID").append('<option value="">= chose Region =</option>');
                    $("#RegionID").empty();
                    $("#RegionID").append('<option value="">= chose Region =</option>');
                    $.each(result, function (index, item) {
                        $("#RegionID").append('<option value="' + item.ID + '">' + item.RegionName + '</option>');
                    });
                },
            });
        });


        $("#RegionID").change(function () {
            var vId = $(this).val();
            $.ajax({
                url: "@Url.Action("GetDistrict", "AJAX")",
                data: { regionId: vId },
                dataType: 'json',
                type: 'GET',
                success: function (result) {
                    $("#DistrictID").empty();
                    $("#DistrictID").append('<option value="">= chose Region =</option>');
                    $.each(result, function (index, item) {
                        $("#DistrictID").append('<option value="' + item.ID + '">' + item.DistrictName + '</option>');
                    });
                },
            });
        });
        $("#btn-cus-save").click(function () {
            $("#form-customers").submit();
            $("#customer-dtl-modal").modal('hide');
        });
    });
</script>