POS/POS.Web/Controllers/ItemsController.cs
using POS.DAL;
using POS.Model;
using POS.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POS.Web.Controllers
{
    [Authorize]
    public class ItemsController : Controller
    {
        // GET: Items
        public ActionResult Index()
        {
            //list Category
            ViewBag.listCategories = new SelectList(CategoriesDAL.GetData(), "ID", "Name");
            //list Inventory
            ViewBag.listInventory = new SelectList(ItemsIventoryDAL.GetData(), "ID", "VariantName");

            List<ListItemViewModel> models = ItemDAL.GetData();
            return View(models);
        }

        public ActionResult Load()
        {
            List<ListItemViewModel> models = ItemDAL.GetData();
            return PartialView("_Index", models);
        }
        public ActionResult Add()
        {
            ViewBag.listCategories = new SelectList(CategoriesDAL.GetData(), "ID", "Name");
            ItemsViewModel models = new ItemsViewModel();
            return PartialView("Add", models);
        }

        public ActionResult AddVariant()
        {
            ItemsVariantViewModel model = new ItemsVariantViewModel();
            return PartialView("AddVariant", model);
        }


        public ActionResult MngInventory()
        {
            ItemsIventoryViewModel model = new ItemsIventoryViewModel();
            return PartialView("MngInventory", model);
        }
        public ActionResult GetCategories(int categoryID)
        {
            List<ItemsViewModel> model = ItemsDAL.GetDataByCategoryID(categoryID);
            return PartialView("_Index", model);
        }

        public ActionResult GetItem(int categoryID)
        {
            List<ItemsViewModel> models = ItemDAL.GetDataByCategoryID(categoryID);
            return PartialView("_Index", models);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(ItemsViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (POSContext context = new POSContext())
                {
                    using (var dbTransaction = context.Database.BeginTransaction())
                    {
                        int UserId = User.Identity.GetUserId<int>();
                        var ListOutlet = context.TOutlet.ToList();
                        int i = 0;
                        foreach (var item in ListOutlet)
                        {
                            Items data = new Items()
                            {
                                Name = model.Name,
                                CategoryID = model.CategoryID,
                                Description = model.Description,
                                CreatedBy = UserId,
                                CreatedOn = DateTime.Now,
                                ModifiedBy = UserId,
                                ModifiedOn = DateTime.Now
                            };
                            context.TItems.Add(data);
                            try { context.SaveChanges(); }
                            catch (Exception) { }
                            i = 0;
                            foreach (var detail in model.VariantNameList)
                            {
                                ItemsVariant data2 = new ItemsVariant()
                                {
                                    ItemID = data.ID,
                                    VariantName = detail,
                                    OutletID = item.ID,
                                    SKU = model.VariantSKU[i],
                                    Price = model.VariantPrice[i],
                                    CreatedBy = UserId,
                                    CreatedOn = DateTime.Now,
                                    ModifiedBy = UserId,
                                    ModifiedOn = DateTime.Now
                                };
                                context.TItemsVariant.Add(data2);
                                try { context.SaveChanges(); }
                                catch (Exception) { }

                                ItemsIventory data3 = new ItemsIventory()
                                {
                                    VariantID = data2.ID,
                                    Beginning = model.Beginning[i],
                                    PurchaseOrder = 0,
                                    Sales = 0,
                                    Transfer = 0,
                                    Adjusment = 0,
                                    Ending = model.Beginning[i],
                                    AlertAt = model.AlertAt[i],
                                    CreatedBy = UserId,
                                    CreatedOn = DateTime.Now,
                                    ModifiedBy = UserId,
                                    ModifiedOn = DateTime.Now
                                };
                                context.TItemsIventory.Add(data3);
                                try { context.SaveChanges(); }
                                catch (Exception) { }

                                i++;
                            }

                        }



                        try
                        {
                            dbTransaction.Commit();
                            return RedirectToAction("Index");
                        }
                        catch (Exception)
                        {
                            dbTransaction.Rollback();
                        }

                    }
                }
            }
            return PartialView("Add", model);
        }

        public ActionResult Edit(int Id)
        {
            //list Category
            ViewBag.listCategories = new SelectList(CategoriesDAL.GetData(), "ID", "Name");
            //list Inventory
            ViewBag.listInventory = new SelectList(ItemsIventoryDAL.GetData(), "ID", "VariantName");

            ListItemViewModel model = ItemsDAL.GetDataById(Id);
            return PartialView("Edit", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ListItemViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (POSContext context = new POSContext())
                {
                    using (var dbTransaction = context.Database.BeginTransaction())
                    {
                        int UserId = User.Identity.GetUserId<int>();
                        int OutletId = 0;
                        OutletId = (int)EmployeeOutletDAL.GetDataOutletByUserId(UserId).OutletID;


                        Items data = context.TItems.Where(x => x.ID == model.ID).FirstOrDefault();
                        if (data != null)
                        {
                            data.Name = model.Name;
                            data.CategoryID = model.CategoryId;
                            data.Description = model.Description;
                            data.CreatedBy = UserId;
                            data.CreatedOn = DateTime.Now;
                            data.ModifiedBy = UserId;
                            data.ModifiedOn = DateTime.Now;
                        }

                        try { context.SaveChanges(); }
                        catch (Exception) { }
                        int i = 0;
                        foreach (var item in model.VariantId)
                        {
                            ItemsVariant data2 = context.TItemsVariant.Where(x => x.ID == item).FirstOrDefault();
                            if (data2 != null)
                            {
                                data2.VariantName = model.VariantName[i];
                                data2.Price = model.VariantPrice[i];
                                data2.SKU = model.VariantSKU[i];
                                data2.CreatedBy = UserId;
                                data2.CreatedOn = DateTime.Now;
                                data2.ModifiedBy = UserId;
                                data2.ModifiedOn = DateTime.Now;
                            };
                            try { context.SaveChanges(); }
                            catch (Exception) { }

                            i++;
                        }
                        i = 0;
                        foreach (var item in model.InventoryId)
                        {
                            ItemsIventory data3 = context.TItemsIventory.Where(x => x.ID == item).FirstOrDefault();
                            if (data3 != null)
                            {
                                data3.Beginning = model.Beginning[i];
                                data3.AlertAt = model.AlertAt[i];
                                data3.CreatedBy = UserId;
                                data3.CreatedOn = DateTime.Now;
                                data3.ModifiedBy = UserId;
                                data3.ModifiedOn = DateTime.Now;
                            }
                            try { context.SaveChanges(); }
                            catch (Exception) { }
                            i++;
                        }
                        try
                        {
                            dbTransaction.Commit();
                            return RedirectToAction("Index");
                        }
                        catch (Exception)
                        {
                            dbTransaction.Rollback();
                        }

                    }
                }
            }
            return PartialView("Edit", model);
        }

        public ActionResult Delete(int Id)
        {
            //list Category
            ViewBag.listCategories = new SelectList(CategoriesDAL.GetData(), "ID", "Name");

POS/POS.Web/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using POS.DAL;
using POS.Model;
using POS.ViewModel;

namespace POS.Web.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {
        // GET: Payment

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Add(PaymentDetailViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (POSContext context = new POSContext())
                {
                    using (var dbTransaction = context.Database.BeginTransaction())
                    {
                        int UserId = User.Identity.GetUserId<int>();
                        int empID = 0;
                        empID = (int)PaymentDAL.GetDataById(UserId).EmployeeID;
                       Payment item = new Payment()
                        {
                            CustomerID = model.CustomerID,
                            EmployeeID = empID,
                            GrandTotal = model.GrandTotal,
                            CreatedBy = UserId,
                            CreatedOn = DateTime.Now,
                            ModifiedBy = UserId,
                            ModifiedOn = DateTime.Now,
                        };
                        context.TPayment.Add(item);
                        context.SaveChanges();
                        int i = 0;
                        foreach(var detail in model.VariantID)
                        {
                            PaymentDetail vDetail = new PaymentDetail()
                            {
                                HeaderID = item.ID,
                                VariantID = detail,
                                Quantity = model.Quantity[i],
                                UnitPrice = model.UnitPrice[i],
                                SubTotal = model.SubTotal[i],
                                CreatedBy = UserId,
                                CreatedOn = DateTime.Now,
                                ModifiedBy = UserId,
                                ModifiedOn = DateTime.Now,
                            };
                            context.TPaymentDetail.Add(vDetail);
                            ItemsIventory item2 = context.TItemsIventory.Where(m => m.VariantID == detail).FirstOrDefault();
                            item2.Sales = model.Quantity[i];

                            i++;
                        }
                        context.SaveChanges();

                        try
                        {
                            dbTransaction.Commit();
                            return RedirectToAction("Add");

                        }
                        catch (Exception)
                        {
                            dbTransaction.Rollback();
                            throw;
                        }
                    }

                }
            }
            return View();
        }

        
    }
}

POS/POS.Web/Controllers/SummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.ViewModel;
using POS.Model;
using POS.DAL;

namespace POS.Web.Controllers
{
    public class SummaryController : Controller
    {
        // GET: Summary
        public ActionResult Index()
        {
            List<ItemIventoryViewModel> model = ItemIventoryDAL.GetDataSum();
            using (POSContext context = new POSContext())

                foreach (var item in model)
                {
                    ItemsIventory data = context.TItemsIventory.Where(m => m.ID == item.ID).FirstOrDefault();
                    data.Ending = item.Beginning + item.PurchaseOrder + item.Adjusment - item.Sales - item.Transfer;
                    context.SaveChanges();
                }


            return View(model);
        }
    }
}

POS/POS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Net 95 Mart</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="hold-transition skin-blue layout-top-nav">
    <div class="wrapper">
        @Html.Partial("_LayoutHeader")
        <div class="content-wrapper">
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>@ViewBag.SubTitle</small>
                </h1>
                <ol class="breadcrumb">
                    <li class="active"><!--<i class="fa fa-dashboard"></i>--><a href="@ViewBag.TitleUrl"> @ViewBag.Title </a></li>
                    <li><a href="@ViewBag.SubTitleUrl"> @ViewBag.SubTitle</a></li>
                </ol>
            </section>
            <section class="content">
                @RenderBody()
            </section>
        </div>
        @Html.Partial("_LayoutFooter")
        @Html.Partial("_LayoutSidebarControl")
        <div class="control-sidebar-bg"></div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("menu", required: false)
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/adminlte")
    @RenderSection("scripts", required: false)
</body>
</html>

POS/POS.Web/Views/Shared/_LayoutFooter.cshtml
<footer class="main-footer">
    <!--
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.3.2
    </div>
    <strong>Copyrights | MVC Application Bartosz Rachwal (AIST) | Layout &copy; 2014-2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights
    reserved.
    //-->
</footer>

POS/POS.Web/Views/Shared/_LayoutHeader.cshtml
<header class="main-header">
    <nav class="navbar navbar-static-top" role="navigation">
        <!--<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button"><span class="sr-only">Toggle navigation</span></a>-->
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse pull-left" id="navbar-collapse" style="padding-left:10px;">
            <ul class="nav navbar-nav">
                <li id="dashboard-menu"><a href="#"><i class="fa fa-dashboard"></i> Net 95 Mart</a></li>
                <li id="dashboard-menu"><a href="@Url.Action("Index","Summary")"><i class="fa fa-history"></i>Summary</a></li>
            </ul>
        </div>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Input Data <span class="caret"></span></a>
                    <ul class="dropdown-menu role="menu">
                        <li><a href="@Url.Action("Index","Categories")">Categories</a></li>
                        <li><a href="@Url.Action("Index","Items")">Items</a></li>
                        <li><a href="@Url.Action("Index","Suppliers")">Suppliers</a></li>
                        
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Transaction <span class="caret"></span></a>
                    <ul class="dropdown-menu role=" menu">
                        <li><a href="@Url.Action("Add","Payment")">Payment</a></li>
                        <li><a href="@Url.Action("Index","PurchaseOrder")">Purchase Order</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Items Stock <span class="caret"></span></a>
                    <ul class="dropdown-menu role=" menu">
                        <li><a href="@Url.Action("Index","Adjustment")">Adjusment</a></li>
                        <li><a href="@Url.Action("Index","Transfer")">Transfer</a></li>
                    </ul>
                </li>
                
                @Html.Partial("_LoginPartial")
                
            </ul>
        </div>
    </nav>
</header>

POS/POS.Web/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/plugins/icheck/square/blue")
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>NET 95</b> MART</a>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg">Sign in to start your session</p>
            @RenderBody()
            
        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->
    <!-- jQuery 2.2.3 -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/plugins/icheck")
    @RenderSection("scripts", required: false)
    @section Scripts{
        <script>
            $(function () {
                $('input').iCheck({
                    checkboxClass: 'icheckbox_square-blue',
                    radioClass: 'iradio_square-blue',
                    increaseArea: '20%' // optional
                });
            });
        </script>
    }
</body>
</html>

POS/POS.Web/Views/Shared/_LayoutSidebar.cshtml
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="~/AdminLTE/dist/img/user.svg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>@User.Identity.GetUserNameIdentifier()</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
            <li id="left-sidebar-menu-dashboard" class="treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li id="left-sidebar-menu-dashboard-dashboardV1"><a href="@Url.Action("DashboardV1", "Home")"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
                    <li id="left-sidebar-menu-dashboard-dashboardV2"><a href="@Url.Action("DashboardV2", "Home")"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
                </ul>
            </li>
            <li id="left-sidebar-menu-widgets">
                <a href="@Url.Action("Index", "Widgets")">
                    <i class="fa fa-th"></i> <span>Widgets</span>
                    <small class="label pull-right bg-green">new</small>
                </a>
            </li>
            <li id="left-sidebar-menu-charts" class="treeview">
                <a href="#">
                    <i class="fa fa-pie-chart"></i>
                    <span>Charts</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li id="left-sidebar-menu-charts-chartjs"><a href="@Url.Action("ChartJs", "Charts")"><i class="fa fa-circle-o"></i> ChartJS</a></li>
                    <li id="left-sidebar-menu-charts-morris"><a href="@Url.Action("Morris", "Charts")"><i class="fa fa-circle-o"></i> Morris</a></li>
                    <li id="left-sidebar-menu-charts-flot"><a href="@Url.Action("Flot", "Charts")"><i class="fa fa-circle-o"></i> Flot</a></li>
                    <li id="left-sidebar-menu-charts-inline"><a href="@Url.Action("Inline", "Charts")"><i class="fa fa-circle-o"></i> Inline charts</a></li>
                </ul>
            </li>
            <li id="left-sidebar-menu-elements" class="treeview">
                <a href="#">
                    <i class="fa fa-laptop"></i>
                    <span>UI Elements</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li id="left-sidebar-menu-elements-general"><a href="@Url.Action("General", "Elements")"><i class="fa fa-circle-o"></i> General</a></li>
                    <li id="left-sidebar-menu-elements-icons"><a href="@Url.Action("Icons", "Elements")"><i class="fa fa-circle-o"></i> Icons</a></li>
                    <li id="left-sidebar-menu-elements-buttons"><a href="@Url.Action("Buttons", "Elements")"><i class="fa fa-circle-o"></i> Buttons</a></li>
                    <li id="left-sidebar-menu-elements-sliders"><a href="@Url.Action("Sliders", "Elements")"><i class="fa fa-circle-o"></i> Sliders</a></li>
                    <li id="left-sidebar-menu-elements-timeline"><a href="@Url.Action("Timeline", "Elements")"><i class="fa fa-circle-o"></i> Timeline</a></li>
                    <li id="left-sidebar-menu-elements-modals"><a href="@Url.Action("Modals", "Elements")"><i class="fa fa-circle-o"></i> Modals</a></li>
                </ul>
            </li>
            <li id="left-sidebar-menu-forms" class="treeview">
                <a href="#">
                    <i class="fa fa-edit"></i> <span>Forms</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li id="left-sidebar-menu-forms-general"><a href="@Url.Action("General", "Forms")"><i class="fa fa-circle-o"></i> General Elements</a></li>
                    <li id="left-sidebar-menu-forms-advanced"><a href="@Url.Action("Advanced", "Forms")"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
                    <li id="left-sidebar-menu-forms-editors"><a href="@Url.Action("Editors", "Forms")"><i class="fa fa-circle-o"></i> Editors</a></li>
                </ul>
            </li>
            <li id="left-sidebar-menu-tables" class="treeview">
                <a href="#">
                    <i class="fa fa-table"></i> <span>Tables</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li id="left-sidebar-menu-tables-simple"><a href="@Url.Action("Simple", "Tables")"><i class="fa fa-circle-o"></i> Simple tables</a></li>
                    <li id="left-sidebar-menu-tables-data"><a href="@Url.Action("Data", "Tables")"><i class="fa fa-circle-o"></i> Data tables</a></li>
                </ul>
            </li>
            <li id="left-sidebar-menu-calendar">
                <a href="@Url.Action("Index", "Calendar")">
                    <i class="fa fa-calendar"></i>
                    <span>Calendar</span>
                    <small class="label pull-right bg-red">3</small>
                </a>
            </li>
            <li id="left-sidebar-menu-mailbox" class="treeview">
                <a href="#">
                    <i class="fa fa-envelope"></i> <span>Mailbox</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li id="left-sidebar-menu-mailbox-inbox"><a href="@Url.Action("Inbox", "Mailbox")">Inbox <span class="label label-primary pull-right">13</span></a></li>
                    <li id="left-sidebar-menu-mailbox-compose"><a href="@Url.Action("Compose", "Mailbox")">Compose</a></li>
                    <li id="left-sidebar-menu-mailbox-read"><a href="@Url.Action("Read", "Mailbox")">Read</a></li>
                </ul>
            </li>
            <li id="left-sidebar-menu-examples" class="treeview">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Examples</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li id="left-sidebar-menu-examples-invoice"><a href="@Url.Action("Invoice", "Examples")"><i class="fa fa-circle-o"></i> Invoice</a></li>
                    <li id="left-sidebar-menu-examples-profileex"><a href="@Url.Action("ProfileEx", "Examples")"><i class="fa fa-circle-o"></i> Profile</a></li>
                    <li id="left-sidebar-menu-examples-login"><a href="@Url.Action("Login", "Examples")"><i class="fa fa-circle-o"></i> Login</a></li>
                    <li id="left-sidebar-menu-examples-register"><a href="@Url.Action("Register", "Examples")"><i class="fa fa-circle-o"></i> Register</a></li>
                    <li id="left-sidebar-menu-examples-lockscreen"><a href="@Url.Action("Lockscreen", "Examples")"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
                    <li id="left-sidebar-menu-examples-p404"><a href="@Url.Action("P404", "Examples")"><i class="fa fa-circle-o"></i> 404 Error</a></li>
                    <li id="left-sidebar-menu-examples-p500"><a href="@Url.Action("P500", "Examples")"><i class="fa fa-circle-o"></i> 500 Error</a></li>
                    <li id="left-sidebar-menu-examples-blank"><a href="@Url.Action("Blank", "Examples")"><i class="fa fa-circle-o"></i> Blank Page</a></li>
                    <li id="left-sidebar-menu-examples-pace"><a href="@Url.Action("Pace", "Examples")"><i class="fa fa-circle-o"></i> Pace Page</a></li>
                </ul>
            </li>
            <li id="left-sidebar-menu-multilevel" class="treeview">
                <a href="#">
                    <i class="fa fa-share"></i> <span>Multilevel</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                    <li>
                        <a href="#"><i class="fa fa-circle-o"></i> Level One <i class="fa fa-angle-left pull-right"></i></a>
                        <ul class="treeview-menu">
                            <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                            <li>
                                <a href="#"><i class="fa fa-circle-o"></i> Level Two <i class="fa fa-angle-left pull-right"></i></a>
                                <ul class="treeview-menu">
                                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                </ul>
            </li>
            <li id="left-sidebar-menu-documentation">
                <a href="@Url.Action("Index", "Documentation")">
                    <i class="fa fa-book"></i>
                    <span>Layout Documentation</span>
                </a>
            </li>
            <li class="header">LABELS</li>
            <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>
        </ul>
    </section>
</aside>